In [1]:
from absenteeism_module import *

In [2]:
model = absenteeism_model('model','scaler')
model.load_and_clean_data('Absenteeism_new_data.csv')
model.predicted_outputs()

/opt/anaconda3/envs/geo-python-student/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.24.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/opt/anaconda3/envs/geo-python-student/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator StandardScaler from version 0.24.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/opt/anaconda3/envs/geo-python-student/lib/python3.8/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

,Reason_1,Reason_2,Reason_3,Reason_4,Transportation Expense,Distance to Work,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,0,0.0,0,1,179,26,30,19,1,0,0,0.627471,1
1,1,0.0,0,0,361,52,28,27,0,1,4,0.740435,1
2,0,0.0,0,1,155,12,34,25,0,2,0,0.958607,1
3,0,0.0,0,1,179,22,40,22,1,2,0,0.889264,1
4,1,0.0,0,0,155,12,34,25,0,2,0,0.960510,1
5,1,0.0,0,0,225,26,28,24,0,1,2,0.848841,1
6,1,0.0,0,0,118,15,46,25,0,2,0,0.983590,1
7,0,0.0,0,1,179,26,30,19,1,0,0,0.627471,1
8,0,0.0,0,1,118,10,37,28,0,0,0,0.984784,1
9,1,0.0,0,0,118,10,37,28,0,0,0,0.985502,1
10,0,0.0,0,1,378,49,36,21,0,2,4,0.398310,0
11,0,0.0,1,0,118,13,50,31,0,1,0,0.996668,1
12,0,0.0,1,0,233,51,31,21,1,1,8,0.678819,1
13,0,0.0,0,1,179,26,30,19,1,0,0,0.627471,1
14,0,0.0,0,0,235,29,48,33,0,1,5,0.992200,1
15,0,0.0,0,0,268,11,33,25,1,0,0,0.770840,1
16,0,0.0,1,0,118,13,50,31,0,1,0,0.996668,1
17,1,0.0,0,0,179,26,30,19,1,0,0,0.638863,1
18,0,0.0,0,1,291,31,40,25,0,1,1,0.838835,1
19,1,0.0,0,0,179,26,30,19,1,0,0,0.638863,1
20,0,0.0,0,1,118,10,37,28,0,0,0,0.984784,1
21,0,0.0,0,1,233,51,31,21,1,1,8,0.676797,1
22,1,0.0,0,0,118,10,37,28,0,0,0,0.985502,1
23,1,0.0,0,0,118,10,37,28,0,0,0,0.985502,1
24,0,0.0,0,1,233,51,31,21,1,1,8,0.676797,1
25,0,0.0,0,1,235,20,43,38,0,1,0,0.997601,1
26,0,0.0,1,0,233,51,31,21,1,1,8,0.678819,1
27,1,0.0,0,0,228,14,58,22,0,2,1,0.917006,1
28,0,0.0,0,1,118,10,37,28,0,0,0,0.984784,1
29,1,0.0,0,0,228,14,58,22,0,2,1,0.917006,1
30,0,0.0,0,1,189,29,33,25,0,2,2,0.940490,1
31,0,0.0,0,1,118,10,37,28,0,0,0,0.984784,1
32,0,0.0,0,1,361,52,28,27,0,1,4,0.730897,1
33,0,0.0,0,1,225,26,28,24,0,1,2,0.842439,1
34,1,0.0,0,0,369,17,31,25,0,3,0,0.678081,1
35,1,0.0,0,0,289,36,33,30,0,2,1,0.954973,1
36,1,0.0,0,0,235,11,37,29,1,1,1,0.956918,1
37,0,0.0,0,0,118,14,40,34,0,1,8,0.997871,1
38,0,0.0,0,0,231,35,39,35,0,2,2,0.995109,1
39,0,0.0,0,0,179,45,53,25,0,1,1,0.971120,1

In [3]:
import pymysql

In [4]:
conn = pymysql.connect(database='predicted_outputs',user = 'root',password = '')

In [5]:
cursor = conn.cursor()

In [6]:
df_new_obs = model.predicted_outputs()
df_new_obs

,Reason_1,Reason_2,Reason_3,Reason_4,Transportation Expense,Distance to Work,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,0,0.0,0,1,179,26,30,19,1,0,0,0.627471,1
1,1,0.0,0,0,361,52,28,27,0,1,4,0.740435,1
2,0,0.0,0,1,155,12,34,25,0,2,0,0.958607,1
3,0,0.0,0,1,179,22,40,22,1,2,0,0.889264,1
4,1,0.0,0,0,155,12,34,25,0,2,0,0.960510,1
5,1,0.0,0,0,225,26,28,24,0,1,2,0.848841,1
6,1,0.0,0,0,118,15,46,25,0,2,0,0.983590,1
7,0,0.0,0,1,179,26,30,19,1,0,0,0.627471,1
8,0,0.0,0,1,118,10,37,28,0,0,0,0.984784,1
9,1,0.0,0,0,118,10,37,28,0,0,0,0.985502,1
10,0,0.0,0,1,378,49,36,21,0,2,4,0.398310,0
11,0,0.0,1,0,118,13,50,31,0,1,0,0.996668,1
12,0,0.0,1,0,233,51,31,21,1,1,8,0.678819,1
13,0,0.0,0,1,179,26,30,19,1,0,0,0.627471,1
14,0,0.0,0,0,235,29,48,33,0,1,5,0.992200,1
15,0,0.0,0,0,268,11,33,25,1,0,0,0.770840,1
16,0,0.0,1,0,118,13,50,31,0,1,0,0.996668,1
17,1,0.0,0,0,179,26,30,19,1,0,0,0.638863,1
18,0,0.0,0,1,291,31,40,25,0,1,1,0.838835,1
19,1,0.0,0,0,179,26,30,19,1,0,0,0.638863,1
20,0,0.0,0,1,118,10,37,28,0,0,0,0.984784,1
21,0,0.0,0,1,233,51,31,21,1,1,8,0.676797,1
22,1,0.0,0,0,118,10,37,28,0,0,0,0.985502,1
23,1,0.0,0,0,118,10,37,28,0,0,0,0.985502,1
24,0,0.0,0,1,233,51,31,21,1,1,8,0.676797,1
25,0,0.0,0,1,235,20,43,38,0,1,0,0.997601,1
26,0,0.0,1,0,233,51,31,21,1,1,8,0.678819,1
27,1,0.0,0,0,228,14,58,22,0,2,1,0.917006,1
28,0,0.0,0,1,118,10,37,28,0,0,0,0.984784,1
29,1,0.0,0,0,228,14,58,22,0,2,1,0.917006,1
30,0,0.0,0,1,189,29,33,25,0,2,2,0.940490,1
31,0,0.0,0,1,118,10,37,28,0,0,0,0.984784,1
32,0,0.0,0,1,361,52,28,27,0,1,4,0.730897,1
33,0,0.0,0,1,225,26,28,24,0,1,2,0.842439,1
34,1,0.0,0,0,369,17,31,25,0,3,0,0.678081,1
35,1,0.0,0,0,289,36,33,30,0,2,1,0.954973,1
36,1,0.0,0,0,235,11,37,29,1,1,1,0.956918,1
37,0,0.0,0,0,118,14,40,34,0,1,8,0.997871,1
38,0,0.0,0,0,231,35,39,35,0,2,2,0.995109,1
39,0,0.0,0,0,179,45,53,25,0,1,1,0.971120,1

In [7]:
df_new_obs.to_csv('df_new_obs.csv')

In [8]:
cursor.execute('SELECT * FROM predicted_outputs;')

40

In [9]:
insert_query = 'INSERT INTO predicted_outputs VALUES '

In [10]:
insert_query

'INSERT INTO predicted_outputs VALUES '

In [11]:
df_new_obs.shape

(40, 13)

In [12]:
for i in range(df_new_obs.shape[0]):
    insert_query += '('
    
    for j in range(df_new_obs.shape[1]):
        insert_query += str(df_new_obs[df_new_obs.columns.values[j]][i]) + ', '
    insert_query = insert_query[:-2] + '), '

In [13]:
insert_query

'INSERT INTO predicted_outputs VALUES (0, 0.0, 0, 1, 179, 26, 30, 19, 1, 0, 0, 0.6274706172877724, 1), (1, 0.0, 0, 0, 361, 52, 28, 27, 0, 1, 4, 0.7404354461676397, 1), (0, 0.0, 0, 1, 155, 12, 34, 25, 0, 2, 0, 0.9586070682053426, 1), (0, 0.0, 0, 1, 179, 22, 40, 22, 1, 2, 0, 0.8892640475364856, 1), (1, 0.0, 0, 0, 155, 12, 34, 25, 0, 2, 0, 0.9605102855010076, 1), (1, 0.0, 0, 0, 225, 26, 28, 24, 0, 1, 2, 0.8488410958480606, 1), (1, 0.0, 0, 0, 118, 15, 46, 25, 0, 2, 0, 0.9835903589745432, 1), (0, 0.0, 0, 1, 179, 26, 30, 19, 1, 0, 0, 0.6274706172877724, 1), (0, 0.0, 0, 1, 118, 10, 37, 28, 0, 0, 0, 0.9847843668838191, 1), (1, 0.0, 0, 0, 118, 10, 37, 28, 0, 0, 0, 0.9855021740381892, 1), (0, 0.0, 0, 1, 378, 49, 36, 21, 0, 2, 4, 0.3983104098839974, 0), (0, 0.0, 1, 0, 118, 13, 50, 31, 0, 1, 0, 0.996668392795785, 1), (0, 0.0, 1, 0, 233, 51, 31, 21, 1, 1, 8, 0.6788192209308425, 1), (0, 0.0, 0, 1, 179, 26, 30, 19, 1, 0, 0, 0.6274706172877724, 1), (0, 0.0, 0, 0, 235, 29, 48, 33, 0, 1, 5, 0.9921996324006568, 1), (0, 0.0, 0, 0, 268, 11, 33, 25, 1, 0, 0, 0.7708401194478122, 1), (0, 0.0, 1, 0, 118, 13, 50, 31, 0, 1, 0, 0.996668392795785, 1), (1, 0.0, 0, 0, 179, 26, 30, 19, 1, 0, 0, 0.6388633704828385, 1), (0, 0.0, 0, 1, 291, 31, 40, 25, 0, 1, 1, 0.8388347976706308, 1), (1, 0.0, 0, 0, 179, 26, 30, 19, 1, 0, 0, 0.6388633704828385, 1), (0, 0.0, 0, 1, 118, 10, 37, 28, 0, 0, 0, 0.9847843668838191, 1), (0, 0.0, 0, 1, 233, 51, 31, 21, 1, 1, 8, 0.6767973015291647, 1), (1, 0.0, 0, 0, 118, 10, 37, 28, 0, 0, 0, 0.9855021740381892, 1), (1, 0.0, 0, 0, 118, 10, 37, 28, 0, 0, 0, 0.9855021740381892, 1), (0, 0.0, 0, 1, 233, 51, 31, 21, 1, 1, 8, 0.6767973015291647, 1), (0, 0.0, 0, 1, 235, 20, 43, 38, 0, 1, 0, 0.9976012493104885, 1), (0, 0.0, 1, 0, 233, 51, 31, 21, 1, 1, 8, 0.6788192209308425, 1), (1, 0.0, 0, 0, 228, 14, 58, 22, 0, 2, 1, 0.9170062975449187, 1), (0, 0.0, 0, 1, 118, 10, 37, 28, 0, 0, 0, 0.9847843668838191, 1), (1, 0.0, 0, 0, 228, 14, 58, 22, 0, 2, 1, 0.9170062975449187, 1), (0, 0.0, 0, 1, 189, 29, 33, 25, 0, 2, 2, 0.9404900479062458, 1), (0, 0.0, 0, 1, 118, 10, 37, 28, 0, 0, 0, 0.9847843668838191, 1), (0, 0.0, 0, 1, 361, 52, 28, 27, 0, 1, 4, 0.7308972669634849, 1), (0, 0.0, 0, 1, 225, 26, 28, 24, 0, 1, 2, 0.8424387983663035, 1), (1, 0.0, 0, 0, 369, 17, 31, 25, 0, 3, 0, 0.6780808822619085, 1), (1, 0.0, 0, 0, 289, 36, 33, 30, 0, 2, 1, 0.9549733769553467, 1), (1, 0.0, 0, 0, 235, 11, 37, 29, 1, 1, 1, 0.9569183209253763, 1), (0, 0.0, 0, 0, 118, 14, 40, 34, 0, 1, 8, 0.9978709371107443, 1), (0, 0.0, 0, 0, 231, 35, 39, 35, 0, 2, 2, 0.995109254118571, 1), (0, 0.0, 0, 0, 179, 45, 53, 25, 0, 1, 1, 0.9711197285997851, 1), '

In [14]:
insert_query = insert_query[:-2] + ';'

In [15]:
insert_query

'INSERT INTO predicted_outputs VALUES (0, 0.0, 0, 1, 179, 26, 30, 19, 1, 0, 0, 0.6274706172877724, 1), (1, 0.0, 0, 0, 361, 52, 28, 27, 0, 1, 4, 0.7404354461676397, 1), (0, 0.0, 0, 1, 155, 12, 34, 25, 0, 2, 0, 0.9586070682053426, 1), (0, 0.0, 0, 1, 179, 22, 40, 22, 1, 2, 0, 0.8892640475364856, 1), (1, 0.0, 0, 0, 155, 12, 34, 25, 0, 2, 0, 0.9605102855010076, 1), (1, 0.0, 0, 0, 225, 26, 28, 24, 0, 1, 2, 0.8488410958480606, 1), (1, 0.0, 0, 0, 118, 15, 46, 25, 0, 2, 0, 0.9835903589745432, 1), (0, 0.0, 0, 1, 179, 26, 30, 19, 1, 0, 0, 0.6274706172877724, 1), (0, 0.0, 0, 1, 118, 10, 37, 28, 0, 0, 0, 0.9847843668838191, 1), (1, 0.0, 0, 0, 118, 10, 37, 28, 0, 0, 0, 0.9855021740381892, 1), (0, 0.0, 0, 1, 378, 49, 36, 21, 0, 2, 4, 0.3983104098839974, 0), (0, 0.0, 1, 0, 118, 13, 50, 31, 0, 1, 0, 0.996668392795785, 1), (0, 0.0, 1, 0, 233, 51, 31, 21, 1, 1, 8, 0.6788192209308425, 1), (0, 0.0, 0, 1, 179, 26, 30, 19, 1, 0, 0, 0.6274706172877724, 1), (0, 0.0, 0, 0, 235, 29, 48, 33, 0, 1, 5, 0.9921996324006568, 1), (0, 0.0, 0, 0, 268, 11, 33, 25, 1, 0, 0, 0.7708401194478122, 1), (0, 0.0, 1, 0, 118, 13, 50, 31, 0, 1, 0, 0.996668392795785, 1), (1, 0.0, 0, 0, 179, 26, 30, 19, 1, 0, 0, 0.6388633704828385, 1), (0, 0.0, 0, 1, 291, 31, 40, 25, 0, 1, 1, 0.8388347976706308, 1), (1, 0.0, 0, 0, 179, 26, 30, 19, 1, 0, 0, 0.6388633704828385, 1), (0, 0.0, 0, 1, 118, 10, 37, 28, 0, 0, 0, 0.9847843668838191, 1), (0, 0.0, 0, 1, 233, 51, 31, 21, 1, 1, 8, 0.6767973015291647, 1), (1, 0.0, 0, 0, 118, 10, 37, 28, 0, 0, 0, 0.9855021740381892, 1), (1, 0.0, 0, 0, 118, 10, 37, 28, 0, 0, 0, 0.9855021740381892, 1), (0, 0.0, 0, 1, 233, 51, 31, 21, 1, 1, 8, 0.6767973015291647, 1), (0, 0.0, 0, 1, 235, 20, 43, 38, 0, 1, 0, 0.9976012493104885, 1), (0, 0.0, 1, 0, 233, 51, 31, 21, 1, 1, 8, 0.6788192209308425, 1), (1, 0.0, 0, 0, 228, 14, 58, 22, 0, 2, 1, 0.9170062975449187, 1), (0, 0.0, 0, 1, 118, 10, 37, 28, 0, 0, 0, 0.9847843668838191, 1), (1, 0.0, 0, 0, 228, 14, 58, 22, 0, 2, 1, 0.9170062975449187, 1), (0, 0.0, 0, 1, 189, 29, 33, 25, 0, 2, 2, 0.9404900479062458, 1), (0, 0.0, 0, 1, 118, 10, 37, 28, 0, 0, 0, 0.9847843668838191, 1), (0, 0.0, 0, 1, 361, 52, 28, 27, 0, 1, 4, 0.7308972669634849, 1), (0, 0.0, 0, 1, 225, 26, 28, 24, 0, 1, 2, 0.8424387983663035, 1), (1, 0.0, 0, 0, 369, 17, 31, 25, 0, 3, 0, 0.6780808822619085, 1), (1, 0.0, 0, 0, 289, 36, 33, 30, 0, 2, 1, 0.9549733769553467, 1), (1, 0.0, 0, 0, 235, 11, 37, 29, 1, 1, 1, 0.9569183209253763, 1), (0, 0.0, 0, 0, 118, 14, 40, 34, 0, 1, 8, 0.9978709371107443, 1), (0, 0.0, 0, 0, 231, 35, 39, 35, 0, 2, 2, 0.995109254118571, 1), (0, 0.0, 0, 0, 179, 45, 53, 25, 0, 1, 1, 0.9711197285997851, 1);'

In [16]:
cursor.execute(insert_query)

40

In [17]:
conn.commit()

In [18]:
conn.close()